### ISSUE TITLE
Wrapper for Penpot for inclusion in Flathub?

### ISSUE THREAD

**Issue by RasheedAZ** [vikdevelop/photopea_app#4]
Hi Vik. Really appreciate your wrappers for Photopea and Canva. Sorry, I know this is probably not the right place to ask but I didn't know how else to get in touch:

Can you please make wrapper for @penpot? It is a free and open source prototyping tool and great alternative to Figma:

https://github.com/penpot/penpot

It's in early stages but usable in my experience and promising. If it gets listed on @flathub that would be a good promotion for it among Linux users  especially as it's open source.

Thanks :)

**Comment by vikdevelop** [comment]
Ok, I'll think about it :)

**Comment by vikdevelop** [comment]
I created repository [vikdevelop/penpot](https://github.com/vikdevelop/penpot). I plan to add it to the flathub.

**Comment by vikdevelop** [comment]
@RasheedAZ I created repository [vikdevelop/penpot](https://github.com/vikdevelop/penpot). I plan to add it to the flathub.
