### ISSUE TITLE
Unable to open files using drag&drop

### ISSUE THREAD

**Issue by Kukulkano** [vikdevelop/photopea_app#5]
Hi. I like your wrapper very much. It makes things more easy. 

Sadly, I'm unable to open any images using drag&drop (eg from doplhin or xnview to your app). I'm on Linux (OpenSUSE x64).

**Comment by vikdevelop** [comment]
Hello, it is possible to drag & drop files, but only from the ~/Downloads folder, due to Flatpak permissions. If you want to allow access to another folder, you can do it using Flatseal app.
