### ISSUE TITLE
Unable top open editor using comandline to open an image directly

### ISSUE THREAD

**Issue by Kukulkano** [vikdevelop/photopea_app#6]
I wanted to link your app with photopea inside as a target for images. So, I tried to submit the image path to the flaptpack in several ways, but with no success...

`flatpak run com.github.vikdevelop.photopea_app ~/images/someimage.jpg`

It does not work. The same for

`flatpak run com.github.vikdevelop.photopea_app --file-forwarding @@ ~/images/someimage.jpg @@`

or

`flatpak run com.github.vikdevelop.photopea_app --file-forwarding @@u ~/images/someimage.jpg @@`

Am I doing it wrong or is that something missing?

**Comment by vikdevelop** [comment]
This unfortunately doesn't work as the application is the Electron app actually, not a native app.
